[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = ["node_modules", ".venv", ".runtime", "dist", "build"]

[tool.ruff.lint]
select = [
  "E","F",      # pycodestyle/pyflakes
  "I",          # isort (import order)
  "B",          # flake8-bugbear
  "UP",         # pyupgrade
  "ASYNC",      # flake8-async
  "RUF",        # ruff rules
]
ignore = [
  "E501",       # line-length (let formatter handle wrapping)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint.isort]
known-first-party = ["aimodel", "file_read"]
combine-as-imports = true

[tool.mypy]
python_version = "3.11"
plugins = []
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_optional = true
strict_equality = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = false
ignore_missing_imports = true
show_error_codes = true
pretty = true
exclude = '(?x)(^node_modules/|^\.venv/|^\.runtime/|/dist/|/build/)'

[tool.vulture]
min_confidence = 70
paths = ["aimodel/file_read"]
exclude = ["**/tests/**", "**/.venv/**", "**/node_modules/**"]
