name = "lic-server"
main = "worker-licensing.ts"
compatibility_date = "2024-09-01"

[durable_objects]
bindings = [
  { name = "LICENSES", class_name = "LicenseStore" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LicenseStore"]

[vars]
APP_BASE_URL = "https://lic-server.localmind.workers.dev"
PORTAL_RETURN_URL = "https://lic-server.localmind.workers.dev/success"
